version: '3'
services:
  app:
    container_name: openjdk
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pg
  pg:
    container_name: pg
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=first_db
      - POSTGRES_PASSWORD=1234
